### PR TITLE
refactor: Adjust font-size and gap between elements

### PR DESCRIPTION
**Pull request by Moussa-Kalam**
@Moussa-Kalam 
# Improve Fragen section and footer
### Checklist before requesting a review
- [x] Fix the collapsible color
- [x] Reduce the font size of the footer nav list
- [x] Update the font-size of the title above the button of the faqs section
- [x] Change the font-family of the footer list elements

### CODE REVIEW

**Review by gitarecy — APPROVED** [review]
Looks good

**Review by gitarecy — APPROVED** [review]
Looking great

**Review by CynthiaUmuhire — APPROVED** [review]
WOOW! You guys did a great job

**Review by danielerat — APPROVED** [review]
Nice work. The font looks much more appealing now.

**Pull request merged**
