### PR TITLE
Ft/unsere teams

### PR DESCRIPTION
**Pull request by Moussa-Kalam**
@CynthiaUmuhire @danielerat, please review this pull request. 
@gitarecy and @Moussa-Kalam worked on the following section. 

# Implement the **Unsere Teams** section
### Checklist before requesting a review
- [x] Design the Unsere Team section
- [x] Add a screenshot of the video
- [x] Add the skills list  
- [x] Add a picture of smiling coaches with short quotes
- [x] Make the whole section responsive (Mobile, Tablet, Desktop)

### CODE REVIEW

**Review by gitarecy — APPROVED** [review]
Great work :)

**Review by gitarecy — APPROVED** [review]
Even better :)

**Review by danielerat — APPROVED** [review]
Looks good to me, but, on the future change, try to make the skillset a bit more responsive (especially on tables)

**Review by CynthiaUmuhire — APPROVED** [review]
This section is even better than I expected!!!

**Pull request merged**
