### PR TITLE
docs:add a pull request template for our repository

### PR DESCRIPTION
**Pull request by CynthiaUmuhire**
@Moussa-Kalam @danielerat @gitarecy 
# Add a pull request template
### Checklist of what I did
- [x] I designed a PR template to be used we are creating PRs

### CODE REVIEW

**Review by danielerat — APPROVED** [review]
Yes Nice, Looks good. We shall use this one for sure 😉

**Comment by Moussa-Kalam** [comment]
Great. This template look nice and straight to the point.

**Review by Moussa-Kalam — APPROVED** [review]
Great

**Comment by gitarecy** [comment]
Looks good

**Review by gitarecy — APPROVED** [review]
Looks good

**Pull request merged**
