### PR TITLE
refactor: Add request changes to the Qualitat section

### PR DESCRIPTION
**Pull request by Moussa-Kalam**
@Moussa-Kalam 
# Refactor Qualitat section
### Checklist before requesting a review
- [x] Update paragraph font size and width
- [x] Change color of collapsible
- [x] Reduce the size of the highlighter

### CODE REVIEW

**Review by CynthiaUmuhire — APPROVED** [review]
You  guys did a great job

**Comment by Moussa-Kalam** [comment]
> You guys did a great job

Thank you @CynthiaUmuhire

**Review by gitarecy — APPROVED** [review]
Good work

**Review by danielerat — APPROVED** [review]
Nice !

**Review by gitarecy — COMMENTED** [review]
Thank you

**Pull request merged**
